version: "3.8"

services:
  # Serviço principal da aplicação (Dev Container)
  app:
    image: mcr.microsoft.com/vscode/devcontainers/java:21
    volumes:
      - ../..:/workspace:cached
    working_dir: /workspace
    command: sleep infinity
    depends_on:
      - mongodb
    networks:
      - highschool-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://dev:dev123@mongodb:27017/highschool

  mongodb:
    image: mongo:6.0
    container_name: mongodb-highschool
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin123
      - MONGO_INITDB_DATABASE=highschool
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - highschool-network

  # Opcional: MongoDB Express para administração via web
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-highschool
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin123
      - ME_CONFIG_MONGODB_URL=mongodb://admin:admin123@mongodb:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - highschool-network

volumes:
  mongodb_data:
    driver: local

networks:
  highschool-network:
    driver: bridge
